language: python
python:
  - "3.4"
branches:
  only:
    - master
    - develop
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libopencv-dev
      - libeigen3-dev
      - libflann-dev
install:
  - pip install -v pyhamcrest
  - pip install -v coveralls
before_script:
  - export PYTHONPATH='.'
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - cd ~/build/qiubix/DisCODeRunner
  - mkdir -p data/test_tasks
  - python setup.py install
  - install_discode.sh
script:
  - coverage run --source=discoderunner setup.py test
after_success:
  - coveralls
